export const colTableValues = {
  id: 1,
  // these are from an example .apkg
  // crt: 1692925200,
  // mod: 1741941550637,
  // scm: 1741941550635,
  ver: 11,
  dty: 0,
  usn: 0,
  ls: 0,
  conf: {
    schedVer: 2,
    dayLearnFirst: false,
    estTimes: true,
    nextPos: 1,
    addToCur: true,
    collapseTime: 1200,
    curModel: 1741941550636,
    sched2021: true,
    creationOffset: -180,
    sortType: "noteFld",
    activeDecks: [1],
    dueCounts: true,
    sortBackwards: false,
    timeLim: 0,
    newSpread: 0,
    curDeck: 1,
  },
  models: {
    "1711892431823": {
      id: 1711892431823,
      name: "Image Occlusion",
      type: 1,
      mod: 1737635749,
      usn: 0,
      sortf: 0,
      did: null,
      tmpls: [
        {
          name: "Image Occlusion",
          ord: 0,
          qfmt: '{{#Header}}<div>{{Header}}</div>{{/Header}}\n<div style="display: none">{{cloze:Occlusion}}</div>\n<div id="err"></div>\n<div id="image-occlusion-container">\n    {{Image}}\n    <canvas id="image-occlusion-canvas"></canvas>\n</div>\n<script>\ntry {\n    anki.imageOcclusion.setup();\n} catch (exc) {\n    document.getElementById("err").innerHTML = `Error loading image occlusion. Is your Anki version up to date?<br><br>${exc}`;\n}\n</script>\n',
          afmt: '{{#Header}}<div>{{Header}}</div>{{/Header}}\n<div style="display: none">{{cloze:Occlusion}}</div>\n<div id="err"></div>\n<div id="image-occlusion-container">\n    {{Image}}\n    <canvas id="image-occlusion-canvas"></canvas>\n</div>\n<script>\ntry {\n    anki.imageOcclusion.setup();\n} catch (exc) {\n    document.getElementById("err").innerHTML = `Error loading image occlusion. Is your Anki version up to date?<br><br>${exc}`;\n}\n</script>\n\n<div><button id="toggle">Toggle Masks</button></div>\n{{#Back Extra}}<div>{{Back Extra}}</div>{{/Back Extra}}\n',
          bqfmt: "",
          bafmt: "",
          did: null,
          bfont: "",
          bsize: 0,
          id: -7486573076461009266,
        },
      ],
      flds: [
        {
          name: "Occlusion",
          ord: 0,
          sticky: false,
          rtl: false,
          font: "Arial",
          size: 20,
          description: "",
          plainText: false,
          collapsed: false,
          excludeFromSearch: false,
          id: 7787621809648212376,
          tag: 0,
          preventDeletion: true,
        },
        {
          name: "Image",
          ord: 1,
          sticky: false,
          rtl: false,
          font: "Arial",
          size: 20,
          description: "",
          plainText: false,
          collapsed: false,
          excludeFromSearch: false,
          id: -5262007660156621727,
          tag: 1,
          preventDeletion: true,
        },
        {
          name: "Header",
          ord: 2,
          sticky: false,
          rtl: false,
          font: "Arial",
          size: 20,
          description: "hi",
          plainText: false,
          collapsed: false,
          excludeFromSearch: false,
          id: 2091943638272366215,
          tag: 2,
          preventDeletion: true,
        },
        {
          name: "Back Extra",
          ord: 3,
          sticky: false,
          rtl: false,
          font: "Arial",
          size: 20,
          description: "",
          plainText: false,
          collapsed: false,
          excludeFromSearch: false,
          id: -8751572109826615077,
          tag: 3,
          preventDeletion: true,
        },
        {
          name: "Comments",
          ord: 4,
          sticky: false,
          rtl: false,
          font: "Arial",
          size: 20,
          description: "",
          plainText: false,
          collapsed: false,
          excludeFromSearch: false,
          id: -4758395342683967347,
          tag: 4,
          preventDeletion: false,
        },
      ],
      css: "#image-occlusion-canvas {\n    --inactive-shape-color: #ffeba2;\n    --active-shape-color: #ff8e8e;\n    --inactive-shape-border: 1px #212121;\n    --active-shape-border: 1px #212121;\n}\n\n.card {\n    font-family: arial;\n    font-size: 20px;\n    text-align: center;\n    color: black;\n    background-color: white;\n}\n",
      latexPre:
        "\\documentclass[12pt]{article}\n\\special{papersize=3in,5in}\n\\usepackage[utf8]{inputenc}\n\\usepackage{amssymb,amsmath}\n\\pagestyle{empty}\n\\setlength{\\parindent}{0in}\n\\begin{document}\n",
      latexPost: "\\end{document}",
      latexsvg: false,
      req: [[0, "any", [0, 1, 2]]],
      originalStockKind: 6,
    },
    "1692999971515": {
      id: 1692999971515,
      name: "Type-in",
      type: 0,
      mod: 1737638496,
      usn: 0,
      sortf: 0,
      did: null,
      tmpls: [
        {
          name: "Card 1",
          ord: 0,
          qfmt: "{{Front}}\n\n{{type:Back}}",
          afmt: "{{Front}}\n\n<hr id=answer>\n\n{{type:Back}}",
          bqfmt: "",
          bafmt: "",
          did: null,
          bfont: "",
          bsize: 0,
          id: null,
        },
      ],
      flds: [
        {
          name: "Front",
          ord: 0,
          sticky: false,
          rtl: false,
          font: "Arial",
          size: 20,
          description: "",
          plainText: false,
          collapsed: false,
          excludeFromSearch: false,
          id: null,
          tag: null,
          preventDeletion: false,
        },
        {
          name: "Back",
          ord: 1,
          sticky: false,
          rtl: false,
          font: "Arial",
          size: 20,
          description: "",
          plainText: false,
          collapsed: false,
          excludeFromSearch: false,
          id: null,
          tag: null,
          preventDeletion: false,
        },
      ],
      css: ".card {\n    font-family: arial;\n    font-size: 20px;\n    text-align: center;\n    color: black;\n    background-color: white;\n}\n",
      latexPre:
        "\\documentclass[12pt]{article}\n\\special{papersize=3in,5in}\n\\usepackage[utf8]{inputenc}\n\\usepackage{amssymb,amsmath}\n\\pagestyle{empty}\n\\setlength{\\parindent}{0in}\n\\begin{document}\n",
      latexPost: "\\end{document}",
      latexsvg: false,
      req: [[0, "any", [0, 1]]],
      originalStockKind: 3,
    },
  },
  decks: {
    "1741886387121": {
      id: 1741886387121,
      mod: 1741886387,
      name: "endokrin-sistemi",
      usn: 17,
      lrnToday: [0, 0],
      revToday: [0, 0],
      newToday: [0, 0],
      timeToday: [0, 0],
      collapsed: false,
      browserCollapsed: false,
      desc: "",
      dyn: 0,
      conf: 1,
      extendNew: 0,
      extendRev: 0,
      reviewLimit: null,
      newLimit: null,
      reviewLimitToday: null,
      newLimitToday: null,
    },
    "1": {
      id: 1,
      mod: 0,
      name: "Default",
      usn: 0,
      lrnToday: [0, 0],
      revToday: [0, 0],
      newToday: [0, 0],
      timeToday: [0, 0],
      collapsed: true,
      browserCollapsed: true,
      desc: "",
      dyn: 0,
      conf: 1,
      extendNew: 0,
      extendRev: 0,
      reviewLimit: null,
      newLimit: null,
      reviewLimitToday: null,
      newLimitToday: null,
    },
    "1741941370516": {
      id: 1741941370516,
      mod: 1741941370,
      name: "test-deck",
      usn: -1,
      lrnToday: [0, 0],
      revToday: [0, 0],
      newToday: [0, 0],
      timeToday: [0, 0],
      collapsed: false,
      browserCollapsed: false,
      desc: "",
      dyn: 0,
      conf: 1,
      extendNew: 0,
      extendRev: 0,
      reviewLimit: null,
      newLimit: null,
      reviewLimitToday: null,
      newLimitToday: null,
    },
  },
  dconf: {
    "1": {
      id: 1,
      mod: 0,
      name: "Default",
      usn: 0,
      maxTaken: 60,
      autoplay: true,
      timer: 0,
      replayq: true,
      new: {
        bury: false,
        delays: [1.0, 10.0],
        initialFactor: 2500,
        ints: [1, 4, 0],
        order: 1,
        perDay: 20,
      },
      rev: {
        bury: false,
        ease4: 1.3,
        ivlFct: 1.0,
        maxIvl: 36500,
        perDay: 200,
        hardFactor: 1.2,
      },
      lapse: {
        delays: [10.0],
        leechAction: 1,
        leechFails: 8,
        minInt: 1,
        mult: 0.0,
      },
      dyn: false,
      newMix: 0,
      newPerDayMinimum: 0,
      interdayLearningMix: 0,
      reviewOrder: 0,
      newSortOrder: 0,
      newGatherPriority: 0,
      buryInterdayLearning: false,
      fsrsWeights: [],
      fsrsParams5: [],
      desiredRetention: 0.9,
      ignoreRevlogsBeforeDate: "",
      easyDaysPercentages: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0],
      stopTimerOnAnswer: false,
      secondsToShowQuestion: 0.0,
      secondsToShowAnswer: 0.0,
      questionAction: 0,
      answerAction: 0,
      waitForAudio: true,
      sm2Retention: 0.9,
      weightSearch: "",
    },
  },
  tags: "{}",
};

export const newDeck = (timestamp: number, name: string) => ({
  [timestamp.toString()]: {
    id: timestamp,
    name: name,
    desc: "",
    usn: 0,
    collapsed: false,
    browserCollapsed: false,
    newToday: [0, 0],
    revToday: [0, 0],
    lrnToday: [0, 0],
    timeToday: [0, 0],
    dyn: 0,
    extendNew: 10,
    extendRev: 50,
    conf: 1,
    mod: timestamp,
    reviewLimit: null,
    newLimit: null,
    reviewLimitToday: null,
    newLimitToday: null,
  },
});
